version: "3.8"

services:
  app:
    container_name: hazy_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000/
      - TZ=Asia/Ulaanbaatar
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - hazy_network

networks:
  hazy_network:
    external: true