version: '3.8'

services:
  app:
    container_name: hazy_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - BACKEND_URL=http//192.168.0.1
      - JWT_SECRET=invalid
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    # command: "npm start -p 3000"
